# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lunbo1',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=200)),
                ('wen', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=100)),
                ('said1', models.CharField(max_length=100)),
                ('said2', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
            ],
        ),
    ]
