# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lunbo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
