# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190315_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunbo1',
            name='div',
        ),
        migrations.RemoveField(
            model_name='lunbo1',
            name='said1',
        ),
        migrations.RemoveField(
            model_name='lunbo1',
            name='said2',
        ),
    ]
