# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190315_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lunbo1',
            old_name='alt',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lunbo1',
            old_name='wen',
            new_name='trackid',
        ),
        migrations.AlterField(
            model_name='lunbo1',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
