# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190315_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('wen', models.CharField(max_length=300)),
                ('alt', models.CharField(max_length=300)),
                ('said1', models.CharField(max_length=300)),
                ('said2', models.CharField(max_length=300)),
                ('price_good', models.CharField(max_length=300)),
            ],
        ),
    ]
