# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190315_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=100)),
                ('typename', models.CharField(max_length=100)),
            ],
        ),
    ]
