# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_foodtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foodtype',
            new_name='goodtype',
        ),
    ]
